// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SchoolTimeCalc.Data;

#nullable disable

namespace SchoolTimeCalc.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260416085319_AddEncryptedPassword")]
    partial class AddEncryptedPassword
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SchoolTimeCalc.Models.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bundesland")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SchoolTimeCalc.Models.Holiday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SchoolId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId", "StartDate", "EndDate")
                        .IsUnique();

                    b.ToTable("Holidays");
                });

            modelBuilder.Entity("SchoolTimeCalc.Models.WebUntisData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationUserId")
                        .HasColumnType("integer");

                    b.Property<string>("EncryptedPassword")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastHolidaySync")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LessonsJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("RoomsJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Server")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubjectsJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("TeachersJson")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.ToTable("WebUntisData");
                });

            modelBuilder.Entity("SchoolTimeCalc.Models.WebUntisData", b =>
                {
                    b.HasOne("SchoolTimeCalc.Models.ApplicationUser", "ApplicationUser")
                        .WithOne("WebUntisData")
                        .HasForeignKey("SchoolTimeCalc.Models.WebUntisData", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("SchoolTimeCalc.Models.ApplicationUser", b =>
                {
                    b.Navigation("WebUntisData");
                });
#pragma warning restore 612, 618
        }
    }
}
